# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: charon_development
  pool: 5
  username: charon
  password: charon

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: charon_test
  pool: 5
  username: charon
  password: 1234

production:
  adapter: postgresql
  encoding: utf8
  database: charon_production
  pool: 5
  username:
  password:
